# Generated by Django 5.1.5 on 2025-03-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
