# Generated by Django 5.1.5 on 2025-03-17 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='participants',
            field=models.ManyToManyField(related_name='joined_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
