# Generated by Django 5.1.7 on 2025-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_is_done_alter_question_text'),
        ('polls', '0004_poll_participants_alter_question_text'),
    ]

    operations = [
    ]
