# Generated by Django 5.1.5 on 2025-03-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_choice_is_correct_studentquizresult_studentresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
