# Generated by Django 5.1.5 on 2025-03-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_poll_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='class_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.class'),
        ),
    ]
